indent

diff --git a/usr/libexec/legacy-dist/deprecation-popup b/usr/libexec/legacy-dist/deprecation-popup
--- a/usr/libexec/legacy-dist/deprecation-popup
+++ b/usr/libexec/legacy-dist/deprecation-popup
@@ -17,24 +17,24 @@ source /usr/libexec/helper-scripts/origins-parser
 status_file=~/.config/legacy-dist/deprecation-notice/dismissed-version-17
 
 if [ "$derivative_major_release_version" = "" ]; then
-   echo "ERROR: version file does not exist or is empty!"
-   exit 1
+  echo "ERROR: version file does not exist or is empty!"
+  exit 1
 fi
 
 if [ "$derivative_major_release_version" -ge "17" ]; then
-   true "INFO: Not yet deprecated, ok."
-   exit 0
+  true "INFO: Not yet deprecated, ok."
+  exit 0
 fi
 
 if test -e /usr/share/qubes/marker-vm; then
-   true "INFO: Not yet deprecated, ok.
+  true "INFO: Not yet deprecated, ok.
 
 Kicksecure 17 and Whonix 17 will remain supported until 1 month after Qubes R4.3 stable has been released.
 
 See also:
 decide availability of Kicksecure, and Whonix 18 (Debian trixie based) on Qubes R4.2 versus R4.3 #10219
 https://github.com/QubesOS/qubes-issues/issues/10219"
-   exit 0
+  exit 0
 fi
 
 title="DEPRECATION NOTICE"
