fix broken gateway-firsttimesetup.desktop desktop icon after Whonix 9 -> Whonix 10 upgrade - https://phabricator.whonix.org/T265

diff --git a/debian/whonix-legacy.preinst b/debian/whonix-legacy.preinst
--- a/debian/whonix-legacy.preinst
+++ b/debian/whonix-legacy.preinst
@@ -48,10 +48,11 @@ eight_dot_x_to_nine_dot_x() {
    dpkg_divert="dpkg"
    dpkg_divert="${dpkg_divert}-divert"
 
+   local old_desktop_icons_list old_desktop_icon
+
    ## {{ 70_cleanup
    ## Have we already done this? Check if lockfile exists.
    if [ ! -f "/var/lib/whonix/do_once/remove_old_8_desktop_icons" ]; then
-      local old_desktop_icons_list old_desktop_icon
       old_desktop_icons_list="
          /home/user/Desktop/whonix-whonixcheck.desktop
          /home/user/Desktop/whonix-contribute.desktop
@@ -86,6 +87,23 @@ eight_dot_x_to_nine_dot_x() {
       touch "/var/lib/whonix/do_once/remove_old_8_desktop_icons"
    fi
    ## }} 70_cleanup
+
+   ## {{ remove_old_9_desktop_icons
+   if [ ! -f "/var/lib/whonix/do_once/remove_old_9_desktop_icons" ]; then
+      old_desktop_icons_list="
+         /home/user/Desktop/gateway-firsttimesetup.desktop
+      "
+      for old_desktop_icon in $old_desktop_icons_list; do
+         if [ -h "$old_desktop_icon" ]; then
+            ## || true in case it fails for some strange reason.
+            unlink "$old_desktop_icon" || true
+         fi
+      done
+      ## Create lockfile.
+      mkdir --parents "/var/lib/whonix/do_once"
+      touch "/var/lib/whonix/do_once/remove_old_9_desktop_icons"
+   fi
+   ## }}
 
    ## {{ 70_deactivate_kmix_autostart
    if [ ! -f "/var/lib/whonix/do_once/remove_kmix_autostart_diversion" ]; then
