release-upgrade

diff --git a/usr/sbin/release-upgrade b/usr/sbin/release-upgrade
--- a/usr/sbin/release-upgrade
+++ b/usr/sbin/release-upgrade
@@ -119,7 +119,7 @@ fi
 if ! test -f /etc/apt/sources.list.d/derivative.list ; then
    true "ERROR: File /etc/apt/sources.list.d/derivative.list does not exist!
 Derivative repository is not enabled. Enable it first before proceeding. See:
-https://www.whonix.org/wiki/Project-APT-Repository
+/wiki/Project-APT-Repository
 Aborting."
    exit 1
 fi
@@ -129,7 +129,7 @@ if [ "$derivative_list_contents" = "" ]; then
    true "ERROR: File /etc/apt/sources.list.d/derivative.list has no valid entries.
 (Maybe only out commented (#) and empty lines.)
 Derivative repository is not enabled. Enable it first before proceeding. See:
-https://www.whonix.org/wiki/Project-APT-Repository
+/wiki/Project-APT-Repository
 Aborting."
    exit 1
 fi
@@ -169,7 +169,7 @@ ERROR:
 Could not fetch package lists. Networking issues?
 Therefore aborting upgrade.
 Recommendation: perform a Standard 'everyday' upgrade beforehand as per:
-https://www.whonix.org/wiki/Operating_System_Software_and_Updates"
+/wiki/Operating_System_Software_and_Updates"
    exit 1
 fi
 
@@ -184,7 +184,7 @@ trap "error_handler" ERR
 
 true "INFO: Backports, testing, unstable should be disabled during release upgrade.
 Removing files which are mentioned in the wiki, if any...
-https://www.whonix.org/wiki/Install_Software"
+/wiki/Install_Software"
 rm -f /etc/apt/sources.list.d/backports.list
 rm -f /etc/apt/sources.list.d/testing.list
 rm -f /etc/apt/sources.list.d/unstable.list
@@ -211,15 +211,15 @@ Check all other files in /etc/apt/sources.list.d if any."
    exit 1
 fi
 
-true "INFO: Download pre release upgrade dependency packages..."
-## just in case: cpp gcc ncal
-## required on workstation for unknown reason: libc6-dev
-if ! apt-get-noninteractive --yes --no-install-recommends --download-only install bsdmainutils gcc sdwdate cpp gcc ncal python-is-python2 libc6-dev fasttrack-archive-keyring ; then
-   true "\
-ERROR: An error was encountered during download of pre release upgrade dependency packages. Recommendation:
-Fix network connection and retry."
-   exit 1
-fi
+# true "INFO: Download pre release upgrade dependency packages..."
+# ## just in case: cpp gcc ncal
+# ## required on workstation for unknown reason: libc6-dev
+# if ! apt-get-noninteractive --yes --no-install-recommends --download-only install bsdmainutils gcc sdwdate cpp gcc ncal python-is-python2 libc6-dev fasttrack-archive-keyring ; then
+#    true "\
+# ERROR: An error was encountered during download of pre release upgrade dependency packages. Recommendation:
+# Fix network connection and retry."
+#    exit 1
+# fi
 
 true "INFO: Download release upgrade..."
 if ! apt-get-noninteractive --yes --no-install-recommends --download-only dist-upgrade ; then
@@ -304,7 +304,7 @@ true "INFO: Running sanity test (post)..."
 dpkg-noninteractive --configure -a
 
 ## Risky. User should review and do manually.
-## https://www.whonix.org/wiki/Whonix_Debian_Packages#Re-install_Meta_Packages_and_Safely_Run_Autoremove
+## /wiki/Debian_Packages#Re-install_Meta_Packages_and_Safely_Run_Autoremove
 #apt-get-noninteractive --yes autoremove
 #dpkg-noninteractive --audit
 #dpkg-noninteractive --configure -a
