improve release-upgrade

diff --git a/usr/sbin/release-upgrade b/usr/sbin/release-upgrade
--- a/usr/sbin/release-upgrade
+++ b/usr/sbin/release-upgrade
@@ -224,6 +224,8 @@ fi
 
 true "INFO: Simulating release upgrade..."
 apt-get-noninteractive --no-install-recommends --simulate dist-upgrade
+true "INFO: Checking if release upgrade is safe or would result in removal of the main meta package... This will take a moment..."
+## Disable xtrace because the following output would be too much of an output flood.
 set +x
 while read -r -d $'\n' line ; do
    read -r first_word second_word _ <<< "$line"
@@ -233,7 +235,9 @@ while read -r -d $'\n' line ; do
    if [ ! "$second_word" = "$meta_package" ]; then
       continue
    fi
-   true "ERROR: Release upgrade would remove meta package $meta_package. Release upgrade aborted!"
+   ## `echo`, not `true` because "set +x" was set above.
+   echo "ERROR: Release upgrade would remove meta package $meta_package. Release upgrade aborted!"
+   exit 1
 done < <( apt-get-noninteractive --no-install-recommends --simulate dist-upgrade )
 set -x
 
